### ISSUE TITLE
Create API Node.Js

### ISSUE THREAD

**Issue by Xeris459** [fadilaaka/app-recommendation-food-CC#1]

**Comment by floatingbug** [comment]
Hi, can you please give a bit more information?

**Comment by Xeris459** [comment]
> Hi, can you please give a bit more information?

I really appreciate the help, but this repository is intended for mutual learning between me and my friends and is now inactive.

This should be private, but our teacher requires us to change the privacy to public, and we forgot to return it back.

I thank you for your help and sorry if the issues we made weren't clear
